### ISSUE TITLE
Animation Error

### ISSUE THREAD

**Issue by psenechal** [selvera/npm-datepicker#18]
Hello,

I'm getting the following error after updating to the latest release (0.9.6).

```Unable to process animations due to the following failed trigger transitions @transformPanel has failed due to: - `query("@fadeInCalendar")` returned zero elements. (Use `query("@fadeInCalendar", { optional: true })` if you wish to allow this.)```

Any ideas if this is something I can handle through configuration? Thanks.

**Comment by xalhera** [comment]
Hi,

Maybe this is due to @angular/material [issue #12199](https://github.com/angular/material2/issues/12199)

I'm providing an [example on stackblitz](https://stackblitz.com/edit/coachcare-datepicker) hoping that could help solving this exception quickly.

Please @matheo can you just confirm if compling using `ng build --prod --build-optimizer` can solve this issue ?

Sincerly

**Comment by matheo** [comment]
@xalhera I'm using Nx 6.1.1 with Angular* 6.1.0 and Angular Material 6.4.1 and I cannot reproduce the issue disabling/enabling `buildOptimizer`, maybe the latest version already fixed the issue?
I recently `ng update`ed all my project to Angular CLI 6.1.1 and it works tho.

**Comment by matheo** [comment]
@psenechal @gltorres If the latest versions of Angular, CLI and Material doesn't work for you guys, I can release a new version without that animation.

**Comment by matheo** [comment]
Ok, I've removed the animation from the `calendar` component and fixed some `strict null checks`. Sadly stackblitz didn't detect the latest `0.9.9` release and couldn't verify that it's ok now, but I bet it is :)

**Comment by xalhera** [comment]
I confirm that the issue is gone with the `0.9.9` release.

Thanks a lot @matheo for your quick update and your great job :)

**Comment by matheo** [comment]
@xalhera Great :D
